// Copyright 2026 Synadia Communications Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tablegen from github.com/nats-io/nats.go v1.53.1; DO NOT EDIT.

package natsapi

// durationTypes holds every exported nats.go type declared as time.Duration,
// keyed by package name and type name.
var durationTypes = map[string]bool{
	"jetstream.DeleteMarkersOlderThan": true,
	"jetstream.PullExpiry":             true,
	"jetstream.PullHeartbeat":          true,
	"nats.AckWait":                     true,
	"nats.DeleteMarkersOlderThan":      true,
	"nats.MaxWait":                     true,
	"nats.PullHeartbeat":               true,
}
