// Copyright 2026 Synadia Communications Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tablegen from github.com/nats-io/nats.go v1.53.1; DO NOT EDIT.

package natsapi

// headers maps every NATS header defined by nats.go to the constants that
// define it, in fix preference order.
var headers = map[string][]HeaderConst{
	"Nats-Expected-Last-Msg-Id":                   {{JetStream, "ExpectedLastMsgIDHeader"}, {Core, "ExpectedLastMsgIdHdr"}},
	"Nats-Expected-Last-Sequence":                 {{JetStream, "ExpectedLastSeqHeader"}, {Core, "ExpectedLastSeqHdr"}},
	"Nats-Expected-Last-Subject-Sequence":         {{JetStream, "ExpectedLastSubjSeqHeader"}, {Core, "ExpectedLastSubjSeqHdr"}},
	"Nats-Expected-Last-Subject-Sequence-Subject": {{JetStream, "ExpectedLastSubjSeqSubjHeader"}},
	"Nats-Expected-Stream":                        {{JetStream, "ExpectedStreamHeader"}, {Core, "ExpectedStreamHdr"}},
	"Nats-Last-Sequence":                          {{JetStream, "LastSequenceHeader"}, {Core, "JSLastSequence"}},
	"Nats-Marker-Reason":                          {{JetStream, "MarkerReasonHeader"}},
	"Nats-Msg-Id":                                 {{JetStream, "MsgIDHeader"}, {Core, "MsgIdHdr"}},
	"Nats-Msg-Size":                               {{Core, "MsgSize"}},
	"Nats-Rollup":                                 {{JetStream, "MsgRollup"}, {Core, "MsgRollup"}},
	"Nats-Schedule":                               {{JetStream, "ScheduleHeader"}},
	"Nats-Schedule-Next":                          {{JetStream, "ScheduleNextHeader"}},
	"Nats-Schedule-Source":                        {{JetStream, "ScheduleSourceHeader"}},
	"Nats-Schedule-TTL":                           {{JetStream, "ScheduleTTLHeader"}},
	"Nats-Schedule-Target":                        {{JetStream, "ScheduleTargetHeader"}},
	"Nats-Schedule-Time-Zone":                     {{JetStream, "ScheduleTimeZoneHeader"}},
	"Nats-Scheduler":                              {{JetStream, "SchedulerHeader"}},
	"Nats-Sequence":                               {{JetStream, "SequenceHeader"}, {Core, "JSSequence"}},
	"Nats-Service-Error":                          {{Micro, "ErrorHeader"}},
	"Nats-Service-Error-Code":                     {{Micro, "ErrorCodeHeader"}},
	"Nats-Stream":                                 {{JetStream, "StreamHeader"}, {Core, "JSStream"}},
	"Nats-Subject":                                {{JetStream, "SubjectHeader"}, {Core, "JSSubject"}},
	"Nats-TTL":                                    {{JetStream, "MsgTTLHeader"}, {Core, "MsgTTLHdr"}},
	"Nats-Time-Stamp":                             {{JetStream, "TimeStampHeaer"}, {Core, "JSTimeStamp"}},
}
