// Copyright 2026 Synadia Communications Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by tablegen from nats-server 2.14.7; DO NOT EDIT.

package natsapi

// serverHeaders lists the NATS header names nats-server uses, including
// those nats.go defines no constant for.
var serverHeaders = []string{
	"Nats-Batch-Commit",
	"Nats-Batch-Id",
	"Nats-Batch-Sequence",
	"Nats-Consumer-Stalled",
	"Nats-Counter-Sources",
	"Nats-Expected-Last-Msg-Id",
	"Nats-Expected-Last-Sequence",
	"Nats-Expected-Last-Subject-Sequence",
	"Nats-Expected-Last-Subject-Sequence-Subject",
	"Nats-Expected-Stream",
	"Nats-Incr",
	"Nats-Last-Consumer",
	"Nats-Last-Sequence",
	"Nats-Last-Stream",
	"Nats-Marker-Reason",
	"Nats-Msg-Id",
	"Nats-Msg-Size",
	"Nats-No-Masking",
	"Nats-Num-Pending",
	"Nats-Pending-Bytes",
	"Nats-Pending-Messages",
	"Nats-Pin-Id",
	"Nats-Request-Info",
	"Nats-Required-Api-Level",
	"Nats-Response-Type",
	"Nats-Rollup",
	"Nats-Schedule",
	"Nats-Schedule-Next",
	"Nats-Schedule-Rollup",
	"Nats-Schedule-Source",
	"Nats-Schedule-TTL",
	"Nats-Schedule-Target",
	"Nats-Schedule-Time-Zone",
	"Nats-Scheduler",
	"Nats-Sequence",
	"Nats-Server-Xkey",
	"Nats-Stream",
	"Nats-Stream-Source",
	"Nats-Subject",
	"Nats-TTL",
	"Nats-Time-Stamp",
	"Nats-Trace-Dest",
	"Nats-Trace-Hop",
	"Nats-Trace-Only",
	"Nats-Trace-Origin-Account",
	"Nats-UpTo-Sequence",
}
