// Copyright 2026 Synadia Communications Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tablegen

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

// serverTree writes a fake nats-server checkout: files maps a path under
// server/ to its content.
func serverTree(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, src := range files {
		p := filepath.Join(dir, "server", name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(src), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestServerHeaders(t *testing.T) {
	dir := serverTree(t, map[string]string{
		"const.go": "package server\n\nconst (\n\tVERSION = \"2.14.7\"\n)\n",
		"stream.go": `package server

// A comment naming "Nats-Commented" does not count.
const (
	JSMsgId          = "Nats-Msg-Id"
	jsExpectedPrefix = "Nats-Expected-"
	JSMsgRollup      = "Nats-Rollup"
)

func f() string { return "Nats-Inline" + "not-a-header" }
`,
		"consumer.go":    "package server\n\nconst JSPullRequestPendingMsgs = \"Nats-Pending-Messages\"\nconst dup = \"Nats-Msg-Id\"\n",
		"stream_test.go": "package server\n\nconst testOnly = \"Nats-Test-Only\"\n",
		"sub/pkg.go":     "package sub\n\nconst traceDest = \"Nats-Trace-Dest\"\n",
	})
	names, version, err := ServerHeaders(dir)
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"Nats-Inline", "Nats-Msg-Id", "Nats-Pending-Messages", "Nats-Rollup", "Nats-Trace-Dest"}
	if !slices.Equal(names, want) {
		t.Errorf("names = %v, want %v", names, want)
	}
	if version != "2.14.7" {
		t.Errorf("version = %q, want 2.14.7", version)
	}
}

func TestServerHeadersMissingCheckout(t *testing.T) {
	if _, _, err := ServerHeaders(filepath.Join(t.TempDir(), "absent")); err == nil {
		t.Error("expected an error for a directory without server/")
	}
}

func TestRenderServerHeaders(t *testing.T) {
	names := []string{"Nats-Msg-Id", "Nats-UpTo-Sequence"}
	a, err := RenderServerHeaders(names, "2.14.7")
	if err != nil {
		t.Fatal(err)
	}
	b, err := RenderServerHeaders(names, "2.14.7")
	if err != nil {
		t.Fatal(err)
	}
	src := string(a)
	if src != string(b) {
		t.Error("two renderings differ")
	}
	for _, want := range []string{
		"// Copyright",
		"// Code generated by tablegen from nats-server 2.14.7; DO NOT EDIT.",
		"package natsapi",
		"var serverHeaders = []string{",
		`"Nats-UpTo-Sequence",`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated source lacks %q:\n%s", want, src)
		}
	}
}
