// Copyright 2026 Synadia Communications Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tablegen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

// ServerHeadersFile is the natsapi file holding the nats-server header list.
const ServerHeadersFile = "server_headers_table.go"

var serverHeaderRe = regexp.MustCompile(`^Nats-[A-Za-z0-9-]+$`)

// ServerHeaders returns the header names nats-server uses: every string
// literal of the form Nats-<letters, digits, dashes> not ending in a dash
// (those are prefixes) in the non-test Go files under dir/server, sorted and
// unique, and the server VERSION constant. Comments do not contribute.
func ServerHeaders(dir string) (names []string, version string, err error) {
	root := filepath.Join(dir, "server")
	seen := make(map[string]bool)
	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.SkipObjectResolution)
		if err != nil {
			return err
		}
		ast.Inspect(f, func(n ast.Node) bool {
			switch n := n.(type) {
			case *ast.ValueSpec:
				if f.Name.Name == "server" && len(n.Names) == 1 && n.Names[0].Name == "VERSION" && len(n.Values) == 1 {
					if v, ok := stringLit(n.Values[0]); ok {
						version = v
					}
				}
			case *ast.BasicLit:
				if v, ok := stringLit(n); ok && serverHeaderRe.MatchString(v) && !strings.HasSuffix(v, "-") {
					seen[v] = true
				}
			}
			return true
		})
		return nil
	})
	if err != nil {
		return nil, "", err
	}
	if version == "" {
		return nil, "", fmt.Errorf("%s: no VERSION constant; not a nats-server checkout", root)
	}
	for name := range seen {
		names = append(names, name)
	}
	slices.Sort(names)
	return names, version, nil
}

func stringLit(e ast.Expr) (string, bool) {
	lit, ok := e.(*ast.BasicLit)
	if !ok || lit.Kind != token.STRING {
		return "", false
	}
	v, err := strconv.Unquote(lit.Value)
	return v, err == nil
}

// RenderServerHeaders renders ServerHeadersFile for names taken from
// nats-server version.
func RenderServerHeaders(names []string, version string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(licenseHeader)
	fmt.Fprintf(&b, "// Code generated by tablegen from nats-server %s; DO NOT EDIT.\n\n", version)
	b.WriteString("package natsapi\n\n")
	b.WriteString("// serverHeaders lists the NATS header names nats-server uses, including\n")
	b.WriteString("// those nats.go defines no constant for.\n")
	b.WriteString("var serverHeaders = []string{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q,\n", name)
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}
